#[general]
#  case = "spaveripy"
[general.plugin_registry.plugins]
  harpverify = "/home/sp3c/deode_project/deode_plugins/"
[suite_control]
  suite_definition = "HarpverifySuiteDefinition"
[submission]
  submit_types = ["background_vm", "background_hpc", "parallel", "gnu", "serial", "harpverify_group"]

[submission.harpverify_group]
  SCHOST = "hpc"                             # Refers to the submission group in troika
  tasks = ["LinkOBSFCTABLES", "Verification", "Filesave"]
  WRAPPER = ""

[submission.harpverify_group.BATCH]
  NAME = "#SBATCH --job-name=@TASK_NAME@"
  NODES = "#SBATCH --nodes=1"
  NTASKS = "#SBATCH --ntasks=1"
  WALLTIME = "#SBATCH --time=01:05:00"

[submission.harpverify_group.ENV]
  DEODE = "awesome"
  DUSER = "aut6432"
  HUSER = "sp3c"
  HARPSCRIPTS_HOME = "/home/sp3c/deode_project/oper-harp-verif/"
  VERIF_HOME= "/ec/res4/hpcperm/sp3c/deode_project/deode_harp_output/"
  REF_SQLITES="/ec/res4/hpcperm/sp3c/deode_project/deode_harp_output/FCTABLE/"
  OBSTABLES_PATH="/ec/res4/hpcperm/sp3c/deode_project/deode_harp_output/OBSTABLE_MERGED/"
  REF_NAME="Global_DT"
  ECFS_ARCHIVE_RELPATH="/deode/HARP_VERIF/cases/"
  DCMDB_DIR="/home/sp3c/deode_project/dcmdb/"
  DW_DIR="/home/sp3c/deode_project/Deode-Workflow"
  RDSS_PATH="/ec/res4/hpcperm/sp3c/deode_project/deode_harp_output/cases/iekm/"
  PNGS_PATH="/ec/res4/hpcperm/sp3c/deode_project/deode_harp_output/casesplots/iekm/"

[submission.harpverify_group.MODULES]
  ECFLOW = ["load", "ecflow"]
  PYTHON311 = ["load", "python3/3.11.8-01"]
  R433 = ["load", "R/4.3.3"]
